export function buildReport(
  input: string,
  result: any,
  reply: string
) {
  const time = new Date().toLocaleString();

  return `
FRAUD INCIDENT REPORT
Generated by SignalSafe
--------------------------------------------

Date: ${time}

Risk Level: ${result.verdict}
Risk Score: ${result.riskScore}/100

Summary:
${result.summary}

Red Flags:
${(result.redFlags || []).map((r: string) => `- ${r}`).join("\n")}

Recommended Actions:
${(result.recommendedActions || []).map((r: string) => `- ${r}`).join("\n")}

Original Message:
"${input}"

Suggested Response Sent:
"${reply}"

--------------------------------------------
This report documents a suspected fraud attempt.
User is advised not to send funds without independent verification.
`;
}
